image: maven:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/

unit-test-job:
  stage: test
  script:
    - mvn test